include: package:effective_dart/analysis_options.yaml
linter:
  rules:
    public_member_api_docs: false
analyzer:
  exclude: [build/**]
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
